wandb_version: 1

batch_size:
  desc: null
  value: 100
num_epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.001
drop_rate:
  desc: null
  value: 0.5
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697693049.361562
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.15.2
      8:
      - 5
